config/routes.rb
ProSim::Application.routes.draw do
   
  get "cst_doc/index"

  resources :bim_models

  resources :aws

   match '/ifc_objects/view' => 'ifc_objects#svg_viewer'
   match '/ifc_objects/count_by_code' => 'ifc_objects#count_by_code'
   match '/ifc_objects/count_by_code_by_floor' => 'ifc_objects#count_by_code_by_floor'
   resources :ifc_objects   
   match '/mmc' => 'multi_model_containers#index'
   match '/cache' => 'draw_panels#show_all'
    match '/multi_model_containers/:multi_model_container_id/primary_models/object' => 'primary_models#object_models'
    resources :multi_model_containers do
    resources :link_models
    resources :primary_models do
    resources :mm_contents do
    resources :mm_files    
    end    
    end  
  end

  
      
  resources :sim_models do
    resources :project_monitors
    resources :construction_sites
    resources :draw_panels
    resources :task_lists do
      resources :tasks  do
        resources :task_attributes , :only =>[:create, :destroy]
      end
    end
    resources :process_pools
    resources :resource_pools do
      resources :sim_resources
      resources :tower_cranes
    end
    resources :gannt_charts
    resources :sim_szenarios do
      resources :sim_results
    end   
  end
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  devise_for :users  
  resources :rpms
  resources :sim_events , :only =>[:index]
  resources :events_reports, :only =>[:index]
  resources :sim_events do
    collection {post :search, to: 'sim_events#index'}
  end
  
  resources :standard_resources
  resources :qto_items
  resources :building_elements
  resources :links
  resources :lv_items  
  resources :attributs
  resources :standard_colors
  resources :bim_filters    
  resources :task_attributes

  root :to => 'welcome#index'
  
  
  

end

app/models/project_monitor.rb
class ProjectMonitor < ActiveRecord::Base
  belongs_to :sim_model
  attr_accessible :name, :sim_model_id
end

app/controllers/project_monitors_controller.rb
class ProjectMonitorsController < ApplicationController
  before_filter :authenticate_user!
  # GET /project_monitors
  # GET /project_monitors.json
  def index
    @sim_model = SimModel.find(params[:sim_model_id])
    @project_monitors =ProjectMonitor.find_all_by_sim_model_id(@sim_model.id)
    if @project_monitors.size == 1
      redirect_to "/sim_models/" + @sim_model.id.to_s + "/project_monitors/" + @project_monitors.first.id.to_s
      return
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_monitors }
    end
  end

  # GET /project_monitors/1
  # GET /project_monitors/1.json
  def show
    @sim_model = SimModel.find(params[:sim_model_id])
    @project_monitor = ProjectMonitor.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_monitor }
    end
  end

  # GET /project_monitors/new
  # GET /project_monitors/new.json
  def new
    @sim_model = SimModel.find(params[:sim_model_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_monitor }
    end
  end

  # GET /project_monitors/1/edit
  def edit
    @sim_model = SimModel.find(params[:sim_model_id])
    @project_monitor = ProjectMonitor.find(params[:id])
  end

  # POST /project_monitors
  # POST /project_monitors.json
  def create
    @sim_model = SimModel.find(params[:sim_model_id])
    @project_monitor = @sim_model.project_monitors.new(params[:project_monitor])
    respond_to do |format|
      if @project_monitor.save
        format.html { redirect_to sim_model_project_monitors_url, notice: 'Project monitor was successfully created.' }
        format.json { render json: sim_model_project_monitors_url, status: :created, location: @project_monitor }
      else
        format.html { render action: "new" }
        format.json { render json: @project_monitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_monitors/1
  # PUT /project_monitors/1.json
  def update
    @project_monitor = ProjectMonitor.find(params[:id])

    respond_to do |format|
      if @project_monitor.update_attributes(params[:project_monitor])
        format.html { redirect_to sim_model_project_monitors_url, notice: 'Project monitor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_monitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_monitors/1
  # DELETE /project_monitors/1.json
  def destroy
    @project_monitor = ProjectMonitor.find(params[:id])
    @project_monitor.destroy

    respond_to do |format|
      format.html { redirect_to sim_model_project_monitors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/project_monitors_helper.rb
module ProjectMonitorsHelper
end

app/views/project_monitors/_form.html.erb
<% @project_monitor =@sim_model.project_monitors.build if  @project_monitor == nil%>
<%= form_for([@sim_model,@project_monitor]) do |f| %>
  <% if @project_monitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_monitor.errors.count, "error") %> prohibited this project_monitor from being saved:</h2>

      <ul>
      <% @project_monitor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_monitors/edit.html.erb
<h3>Editing project monitor</h3>

<%= render 'form' %>

<%= link_to 'Show', sim_model_project_monitor_path %> |
<%= link_to 'Back', sim_model_project_monitors_path %>

app/views/project_monitors/index.html.erb
<%= stylesheet_link_tag    "table", :media => "all" %>
<h3>Listing project monitors</h3>
<%= link_to image_tag("icons/plus.png", :border => 0) + t("New Project monitor"), new_sim_model_project_monitor_path %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_monitors.each do |project_monitor| %>
  <tr>   
    <td><%= project_monitor.name %></td>    
    <td><%= link_to 'Show', "project_monitors/#{project_monitor.id}" %></td>
    <td><%= link_to 'Edit', "project_monitors/#{project_monitor.id}/edit" %></td>
    <td><%= link_to 'Destroy', "project_monitors/#{project_monitor.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'Back to simulation model:' + @sim_model.name, sim_model_path(@sim_model) %>

app/views/project_monitors/new.html.erb
<h3>New project monitor</h3>

<%= render 'form' %>

app/views/project_monitors/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Sim model:</b>
  <%= @project_monitor.sim_model.name %>
</p>
<p>
  <b>Name:</b>
  <%= @project_monitor.name %>
</p>

<% @component =@project_monitor %>
<%= render "shared/image_player" %>

<%= link_to 'Edit', edit_sim_model_project_monitor_path(@project_monitor) if not @project_monitor.sim_model.readonly? %> |
<%= link_to 'Back', sim_model_project_monitors_path %>