config/routes.rb
ProSim::Application.routes.draw do
   
  get "cst_doc/index"

  resources :bim_models

  resources :aws

   match '/ifc_objects/view' => 'ifc_objects#svg_viewer'
   match '/ifc_objects/count_by_code' => 'ifc_objects#count_by_code'
   match '/ifc_objects/count_by_code_by_floor' => 'ifc_objects#count_by_code_by_floor'
   resources :ifc_objects   
   match '/mmc' => 'multi_model_containers#index'
   match '/cache' => 'draw_panels#show_all'
    match '/multi_model_containers/:multi_model_container_id/primary_models/object' => 'primary_models#object_models'
    resources :multi_model_containers do
    resources :link_models
    resources :primary_models do
    resources :mm_contents do
    resources :mm_files    
    end    
    end  
  end

  
      
  resources :sim_models do
    resources :project_monitors
    resources :construction_sites
    resources :draw_panels
    resources :task_lists do
      resources :tasks  do
        resources :task_attributes , :only =>[:create, :destroy]
      end
    end
    resources :process_pools
    resources :resource_pools do
      resources :sim_resources
      resources :tower_cranes
    end
    resources :gannt_charts
    resources :sim_szenarios do
      resources :sim_results
    end   
  end
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  devise_for :users  
  resources :rpms
  resources :sim_events , :only =>[:index]
  resources :events_reports, :only =>[:index]
  resources :sim_events do
    collection {post :search, to: 'sim_events#index'}
  end
  
  resources :standard_resources
  resources :qto_items
  resources :building_elements
  resources :links
  resources :lv_items  
  resources :attributs
  resources :standard_colors
  resources :bim_filters    
  resources :task_attributes

  root :to => 'welcome#index'
  
  
  

end

app/models/sim_model.rb
class SimModel < ActiveRecord::Base
  belongs_to :user   
  has_many :process_pools 
  has_many :sim_events 
  has_many :rpms
  has_many :task_lists
  has_many :sim_resources
  has_many :draw_panels
  has_many :project_monitors
  has_many :tower_cranes
  has_many :resource_pools
  has_many :gannt_charts
  has_many :sim_szenarios  
  has_many :construction_sites 
  attr_accessible :description, :model_tree_path, :name, :results_url, :user_id, :bim_url  
  
  # Prevent creation of new records and modification to existing records
  def readonly?    
    return false
  end
 
  # Prevent objects from being destroyed
  def before_destroy
    
    raise ActiveRecord::ReadOnlyRecord
  end
  
  def self.delete_all
    raise ActiveRecord::ReadOnlyRecord
  end
  
  def delete
    raise ActiveRecord::ReadOnlyRecord
  end
end

app/controllers/sim_models_controller.rb
class SimModelsController < ApplicationController
  before_filter :authenticate_user!
  # GET /sim_models
  # GET /sim_models.json
  def index
    if current_user != nil
    @sim_models = SimModel.includes(:user).where(:user_id => current_user.id).all
    else
      @sim_models = SimModel.all
     end 
    #@sim_models = SimModel.includes(:user).all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sim_models }
    end
  end

  # GET /sim_models/1
  # GET /sim_models/1.json
  def show
    @sim_model = SimModel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sim_model }
    end
  end

  # GET /sim_models/new
  # GET /sim_models/new.json
  def new
    @sim_model = SimModel.new
    @sim_model.user_id = current_user.id
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sim_model }
    end
  end

  # GET /sim_models/1/edit
  def edit
    @sim_model = SimModel.find(params[:id])
  end

  # POST /sim_models
  # POST /sim_models.json
  def create
    @sim_model = SimModel.new(params[:sim_model])
    @sim_model.user_id = current_user.id
    respond_to do |format|
      if @sim_model.save
        format.html { redirect_to @sim_model, notice: 'Sim model was successfully created.' }
        format.json { render json: @sim_model, status: :created, location: @sim_model }
      else
        format.html { render action: "new" }
        format.json { render json: @sim_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sim_models/1
  # PUT /sim_models/1.json
  def update
    @sim_model = SimModel.find(params[:id])

    respond_to do |format|
      if @sim_model.update_attributes(params[:sim_model])
        format.html { redirect_to @sim_model, notice: 'Sim model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sim_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sim_models/1
  # DELETE /sim_models/1.json
  def destroy
    @sim_model = SimModel.find(params[:id])
    @sim_model.destroy

    respond_to do |format|
      format.html { redirect_to sim_models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sim_models_helper.rb
module SimModelsHelper
end

app/views/sim_models/Copy of show.html.erb
<%= stylesheet_link_tag    "table", :media => "all" %>
<%= stylesheet_link_tag    "sim_models", :media => "all" %>
<p>
  <b>Name:</b>
  <%= @sim_model.name %>
</p>
<div class="description"><%= @sim_model.description %></div>
<h2>Simulation szenarios</h2>
<table>
  <tr>
    <th>Szenario</th>
    <th>Description</th>    
    <th>Results</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @sim_model.sim_szenarios.each do |sim_szenario| %>
  <tr>
    <td><%= sim_szenario.name %></td>
    <td><%= sim_szenario.description.html_safe %></td>  
    <td><%= link_to 'Results', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}/sim_results" %></td>  
    <td><%= link_to 'Show', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}" %></td>
    <td><%= link_to 'Edit', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}/edit" %></td>
    <td><%= link_to 'Destroy', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<div style="float:left;padding: 3px">
	<h3><%= t("Inputs") %></h3>
<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/TasksList.png", :border => 0) + raw("<br/>") + t("Task lists"), sim_model_task_lists_path(@sim_model), {:class => 'dock-item'} %>	
</div>

<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/ProcessCatalog.png", :border => 0) + raw("<br/>") + t("Process catalog"), {:action => 'index', :controller => 'rpms'}, {:class => 'dock-item'} %>	
</div>

<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/ResourcePool.png", :border => 0) + raw("<br/>") + t("Resource pool"), sim_model_resource_pools_path(@sim_model), {:class => 'dock-item'} %>	
</div>

<% if @sim_model.multi_model_container_id != nil %>
<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/MMC.png", :border => 0) + raw("<br/>") + "Mefisto MMC", "/multi_model_containers/#{@sim_model.multi_model_container_id}", {:class => 'dock-item'} %>	
</div>
<% end %>

<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/ProductivityFactors.png", :border => 0) + raw("<br/>") + t("Productivity coeff"), "http://bci52.cib.bau.tu-dresden.de:3001/sim/aufwandswerte.php", {:class => 'dock-item'} %>	
</div>

<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/ConstructionSite.png", :border => 0) + raw("<br/>") + t("Construction site"), {:action => 'index', :controller => 'welcome'}, {:class => 'dock-item'} %>	
</div>


</div>
<div style="clear:both">
<h3><%= t("Outputs") %></h3>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/GanntChart.png", :border => 0) + raw("<br/>") + "Gannt Charts", sim_model_gannt_charts_path(@sim_model), {:class => 'dock-item'}%> 
</div>

<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/ProjectMonitor.png", :border => 0) + raw("<br/>") + "Project monitors", sim_model_project_monitors_path(@sim_model), {:class => 'dock-item'}%> 
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/ProcessPool.png", :border => 0) + raw("<br/>") + t("Process pool"), sim_model_process_pools_path(@sim_model), {:class => 'dock-item'} %>	
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/4DVisulazier.png", :border => 0) + raw("<br/>") + "4D Visualization", {:action => 'index', :controller => 'welcome'}, {:class => 'dock-item'} %>
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/DrawPanel.png", :border => 0) + raw("<br/>") + "Drawing panels",sim_model_draw_panels_path(@sim_model) , {:class => 'dock-item'} %>	

</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/viz.png", :border => 0) + raw("<br/>") + "Data Visualization", {:action => 'index', :controller => 'welcome'}, {:class => 'dock-item'} %>
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/Verification.png", :border => 0) + raw("<br/>") + t("Verification"), {:action => 'index', :controller => 'sim_events'}, {:class => 'dock-item'} %>	
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/calendar.png", :border => 0)  + raw("<br/>") + t("Calendar"), {:action => 'index', :controller => 'calendar'}, {:class => 'dock-item'} %>	
</div>
</div>
<div style="clear:both">
<hr>
<h3><%= t("Settings") %></h3>
<div style="float:left;padding: 10px">
<%= link_to  image_tag("icons/colors.png", :border => 0)  + t("Colors"), {:action => 'index', :controller => 'standard_colors'}, {:class => 'dock-item'} %>	
</div>

<div style="float:left;padding: 10px">
<%= link_to  image_tag("icons/Filter.png", :border => 0)  + "BIM filters", {:action => 'index', :controller => 'bim_filters'}, {:class => 'dock-item'} %>	
</div>
<div style="float:left;padding: 10px">
<%= link_to  image_tag("icons/Properties.png", :border => 0)  + "Object Attributes", {:action => 'index', :controller => 'attributs'}, {:class => 'dock-item'} %>	
</div>
</div>
<%= link_to 'Edit', edit_sim_model_path(@sim_model) %> |
<%= link_to 'Back', sim_models_path %>

app/views/sim_models/_form.html.erb
<%= form_for(@sim_model) do |f| %>
  <% if @sim_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sim_model.errors.count, "error") %> prohibited this sim_model from being saved:</h2>

      <ul>
      <% @sim_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :model_tree_path %><br />
    <%= f.text_field :model_tree_path %>
  </div>
  <div class="field">
    <%= f.label :results_url %><br />
    <%= f.text_field :results_url %>
  </div>
    <div class="field">
    <%= f.label :bim_url %><br />
    <%= f.text_field :bim_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sim_models/edit.html.erb
<h1>Editing sim_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @sim_model %> |
<%= link_to 'Back', sim_models_path %>

app/views/sim_models/index.html.erb
<%= stylesheet_link_tag    "sim_models", :media => "all" %>
<h2>Simulation models</h2>
<% @sim_models.each do |sim_model| %>
  	<h3><%= sim_model.name %></h3>
    <div class="description"><%= sim_model.description.html_safe %></div>
    <b>Owner</b>:<%= sim_model.user.name %>(<%= sim_model.user.email %>)<br /><br />	
	<%= link_to image_tag( "/MMCs/" +  sim_model.name + ".png", :border => 0), sim_model %><br />
    <div class="description">    	   
    <%= link_to 'Open', sim_model %>
    <%= link_to 'Edit', edit_sim_model_path(sim_model) %>
    <%= link_to 'Remove', sim_model, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <hr />
<% end %>
<%= link_to 'New Sim model', new_sim_model_path %>

app/views/sim_models/new.html.erb
<h1>New sim_model</h1>

<%= render 'form' %>

<%= link_to 'Back', sim_models_path %>

app/views/sim_models/show.html.erb
<%= stylesheet_link_tag    "table", :media => "all" %>
<%= stylesheet_link_tag    "sim_models", :media => "all" %>
<p>
  <b>Name:</b>
<h2><%= @sim_model.name %></h2>
<%= link_to 'Edit', edit_sim_model_path(@sim_model)   if current_user.name == "Ali Ismail" %> |
<%= link_to 'Back', sim_models_path %>
</p>
<div class="description"><%= @sim_model.description.html_safe %></div>
<h2>Simulation szenarios</h2>
<table>
  <tr>
    <th>Szenario</th>
    <th>Description</th>    
    <th>Results</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>  
<% @sim_model.sim_szenarios.each do |sim_szenario| %>
  <tr>
    <td><%= sim_szenario.name %></td>
    <td><%= sim_szenario.description.html_safe %></td>  
    <td><%= link_to 'Results', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}/sim_results" %></td>  
    <td><%= link_to 'Show', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}" %></td>
    <td><%= link_to 'Edit', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}/edit" if not @sim_model.readonly? %></td>
    <td><%= link_to 'Destroy', "#{sim_szenario.sim_model.id}/sim_szenarios/#{sim_szenario.id}", method: :delete, data: { confirm: 'Are you sure?' } if not @sim_model.readonly?%></td>
  </tr>
<% end %>
</table>
<div style="float:left;padding: 3px">
	<h3><%= t("Inputs") %></h3>
<% if @sim_model.multi_model_container_id != nil %>	
<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/BIM_data.png", :border => 0) + raw("<br/>") + t("BIM models"), "/multi_model_containers/#{@sim_model.multi_model_container_id}/primary_models/object", {:class => 'dock-item'} %>	
</div>	
<% end %>
<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/TasksList.png", :border => 0) + raw("<br/>") + t("Task lists"), sim_model_task_lists_path(@sim_model), {:class => 'dock-item'} %>	
</div>

<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/ResourcePool.png", :border => 0) + raw("<br/>") + t("Resource pool"), sim_model_resource_pools_path(@sim_model), {:class => 'dock-item'} %>	
</div>

<% if @sim_model.multi_model_container_id != nil %>
<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/MMC.png", :border => 0) + raw("<br/>") + "Mefisto MMC", "/multi_model_containers/#{@sim_model.multi_model_container_id}", {:class => 'dock-item'} %>	
</div>
<% end %>


<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/ConstructionSite.png", :border => 0) + raw("<br/>") + "Construction Site", "/sim_models/#{@sim_model.id}/construction_sites", {:class => 'dock-item'} %>	
</div>


<div style="float: left;padding: 3px">
<%= link_to  image_tag("icons/ProductivityFactors.png", :border => 0) + raw("<br/>") + t("Productivity coeff"), aws_path, {:class => 'dock-item'} %>	
</div>


</div>
<div style="clear:both">
<h3><%= t("Outputs") %></h3>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/GanntChart.png", :border => 0) + raw("<br/>") + "Gannt Charts", sim_model_gannt_charts_path(@sim_model), {:class => 'dock-item'}%> 
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/ProjectMonitor.png", :border => 0) + raw("<br/>") + "Project monitors", sim_model_project_monitors_path(@sim_model), {:class => 'dock-item'}%> 
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/DrawPanel.png", :border => 0) + raw("<br/>") + "Drawing panels",sim_model_draw_panels_path(@sim_model) , {:class => 'dock-item'} %>	

</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/Verification.png", :border => 0) + raw("<br/>") + t("Verification"), {:action => 'index', :controller => 'sim_events'}, {:class => 'dock-item'} %>	
</div>
<div style="float:left;padding: 3px">
<%= link_to  image_tag("icons/calendar.png", :border => 0)  + raw("<br/>") + t("Calendar"), "/calendar/2013/3", {:class => 'dock-item'} %>	
</div>
</div>
<div style="clear:both">
<hr>
<h3><%= t("Settings") %></h3>

<div style="float:left;padding: 10px">
<%= link_to  image_tag("icons/aws.png", :border => 0)  + "<br>".html_safe +  t("Aufwandswerte"), {:action => 'index', :controller => 'aws'}, {:class => 'dock-item'} %>
<br /><%= link_to  t("Standard Leistungspositionen"), {:action => 'index', :controller => 'lv_items'}, {:class => 'dock-item'} %> 	
</div>

<div style="float:left;padding: 10px">
<%= link_to  image_tag("icons/rpms.png", :border => 0), {:action => 'index', :controller => 'rpms'}, {:class => 'dock-item'} %>	
</div>

<div style="float:left;padding: 10px">
<%= link_to  image_tag("icons/colors.png", :border => 0)  + "<br>".html_safe + t("Colors"), {:action => 'index', :controller => 'standard_colors'}, {:class => 'dock-item'} %>	
</div>
</div>