config/routes.rb
ProSim::Application.routes.draw do
   
  get "cst_doc/index"

  resources :bim_models

  resources :aws

   match '/ifc_objects/view' => 'ifc_objects#svg_viewer'
   match '/ifc_objects/count_by_code' => 'ifc_objects#count_by_code'
   match '/ifc_objects/count_by_code_by_floor' => 'ifc_objects#count_by_code_by_floor'
   resources :ifc_objects   
   match '/mmc' => 'multi_model_containers#index'
   match '/cache' => 'draw_panels#show_all'
    match '/multi_model_containers/:multi_model_container_id/primary_models/object' => 'primary_models#object_models'
    resources :multi_model_containers do
    resources :link_models
    resources :primary_models do
    resources :mm_contents do
    resources :mm_files    
    end    
    end  
  end

  
      
  resources :sim_models do
    resources :project_monitors
    resources :construction_sites
    resources :draw_panels
    resources :task_lists do
      resources :tasks  do
        resources :task_attributes , :only =>[:create, :destroy]
      end
    end
    resources :process_pools
    resources :resource_pools do
      resources :sim_resources
      resources :tower_cranes
    end
    resources :gannt_charts
    resources :sim_szenarios do
      resources :sim_results
    end   
  end
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  devise_for :users  
  resources :rpms
  resources :sim_events , :only =>[:index]
  resources :events_reports, :only =>[:index]
  resources :sim_events do
    collection {post :search, to: 'sim_events#index'}
  end
  
  resources :standard_resources
  resources :qto_items
  resources :building_elements
  resources :links
  resources :lv_items  
  resources :attributs
  resources :standard_colors
  resources :bim_filters    
  resources :task_attributes

  root :to => 'welcome#index'
  
  
  

end

app/models/resource_pool.rb
class ResourcePool < ActiveRecord::Base
  belongs_to :sim_model
  has_many :tower_cranes
  has_many :sim_resources
  attr_accessible :name, :sim_model_id
end

app/controllers/resource_pools_controller.rb
class ResourcePoolsController < ApplicationController
  before_filter :authenticate_user!
  # GET /resource_pools
  # GET /resource_pools.json
  def index     
    @sim_model = SimModel.find(params[:sim_model_id])
    @resource_pools =ResourcePool.find_all_by_sim_model_id(@sim_model.id)
    if @resource_pools.size == 1
      redirect_to "/sim_models/" + @sim_model.id.to_s + "/resource_pools/" + @resource_pools.first.id.to_s
      return
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resource_pools }
    end
  end

  # GET /resource_pools/1
  # GET /resource_pools/1.json
  def show
    @sim_model = SimModel.find(params[:sim_model_id])    
    @resource_pool = ResourcePool.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resource_pool }
    end
  end

  # GET /resource_pools/new
  # GET /resource_pools/new.json
  def new
    @sim_model = SimModel.find(params[:sim_model_id])
    @resource_pool = ResourcePool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resource_pool }
    end
  end

  # GET /resource_pools/1/edit
  def edit
    @sim_model = SimModel.find(params[:sim_model_id])    
    @resource_pool = ResourcePool.find(params[:id])
  end

  # POST /resource_pools
  # POST /resource_pools.json
  def create
    @sim_model = SimModel.find(params[:sim_model_id])    
    @resource_pool = @sim_model.resource_pools.new(params[:resource_pool])

    respond_to do |format|
      if @resource_pool.save
        format.html { redirect_to sim_model_resource_pools_url, notice: 'Resource pool was successfully created.' }
        format.json { render json: sim_model_resource_pools_url, status: :created, location: @resource_pool }
      else
        format.html { render action: "new" }
        format.json { render json: @resource_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resource_pools/1
  # PUT /resource_pools/1.json
  def update
    @resource_pool = ResourcePool.find(params[:id])
    respond_to do |format|
      if @resource_pool.update_attributes(params[:resource_pool])
        format.html { redirect_to sim_model_resource_pools_url, notice: 'Resource pool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resource_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_pools/1
  # DELETE /resource_pools/1.json
  def destroy
    @resource_pool = ResourcePool.find(params[:id])
    @resource_pool.destroy

    respond_to do |format|
      format.html { redirect_to sim_model_resource_pools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/resource_pools_helper.rb
module ResourcePoolsHelper
end

app/views/resource_pools/_form.html.erb
<% @resource_pool =@sim_model.resource_pools.build if  @resource_pool == nil%>
<%= form_for([@sim_model,@resource_pool]) do |f| %>
  <% if @resource_pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_pool.errors.count, "error") %> prohibited this resource_pool from being saved:</h2>

      <ul>
      <% @resource_pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_pools/edit.html.erb
<h1>Editing resource pool</h1>
<%= render 'form' %>
<%= link_to 'Show', sim_model_resource_pool_path %> |
<%= link_to 'Back', sim_model_resource_pools_path %>

app/views/resource_pools/index.html.erb
<%= stylesheet_link_tag    "table", :media => "all" %>
<h3>Listing resource pools</h3>
<%= link_to image_tag("icons/plus.png", :border => 0) + t("New resource pool"), new_sim_model_resource_pool_path %>
<table>
  <tr>
    <th>Name</th>    
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @resource_pools.each do |resource_pool| %>
  <tr>
    <td><%= resource_pool.name %></td>
    <td><%= link_to 'Show', "resource_pools/#{resource_pool.id}" %></td>
    <td><%= link_to 'Edit', "resource_pools/#{resource_pool.id}/edit" %></td>
    <td><%= link_to 'Destroy', "resource_pools/#{resource_pool.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Back to simulation model:' + @sim_model.name, sim_model_path(@sim_model) %>

app/views/resource_pools/new.html.erb
<h1>New resource_pool</h1>

<%= render 'form' %>

<%= link_to 'Back', sim_model_resource_pools_path %>

app/views/resource_pools/show.html.erb
<%= stylesheet_link_tag    "table", :media => "all" %>
<%= stylesheet_link_tag    "resource_pools", :media => "all" %>

Links: <%= link_to image_tag("icons/kran.png", :border => 0) +  "<br/>Tower cranes".html_safe ,"/sim_models/#{@resource_pool.sim_model.id}/resource_pools/#{@resource_pool.id}/tower_cranes" %>
<p>
  <b>Sim model:</b>
  <%= @resource_pool.sim_model.name %>
</p>
<p>
  <b>Name:</b>
  <%= @resource_pool.name %>
</p>
<%= link_to image_tag("icons/plus.png", :border => 0) + t("New Sim resource"), "/sim_models/#{@resource_pool.sim_model.id}/resource_pools/#{@resource_pool.id}/sim_resources/new" if not @resource_pool.sim_model.readonly? %>
<table>
  <tr>
    <th>Resource Name</th>
    <th>Resource class</th>
    <th>Resource amount</th>
    <th>Delivery time</th>
    <th>Delivery date</th>  
  </tr>
<% @resource_pool.sim_resources.each do |sim_resource| %>
  <tr>
    <td><%= sim_resource.name %></td>
    <td><%= sim_resource.res_class %></td>
    <td><%= sim_resource.res_num %></td>
    <td><%= sim_resource.delivery_time %></td>
    <td><%= sim_resource.delivery_date %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Edit', "/sim_models/#{@resource_pool.sim_model.id}/resource_pools/#{@resource_pool.id}/edit" if not @resource_pool.sim_model.readonly? %> |
<%= link_to 'Back', sim_model_resource_pools_path %>