config/routes.rb
ProSim::Application.routes.draw do
   
  get "cst_doc/index"

  resources :bim_models

  resources :aws

   match '/ifc_objects/view' => 'ifc_objects#svg_viewer'
   match '/ifc_objects/count_by_code' => 'ifc_objects#count_by_code'
   match '/ifc_objects/count_by_code_by_floor' => 'ifc_objects#count_by_code_by_floor'
   resources :ifc_objects   
   match '/mmc' => 'multi_model_containers#index'
   match '/cache' => 'draw_panels#show_all'
    match '/multi_model_containers/:multi_model_container_id/primary_models/object' => 'primary_models#object_models'
    resources :multi_model_containers do
    resources :link_models
    resources :primary_models do
    resources :mm_contents do
    resources :mm_files    
    end    
    end  
  end

  
      
  resources :sim_models do
    resources :project_monitors
    resources :construction_sites
    resources :draw_panels
    resources :task_lists do
      resources :tasks  do
        resources :task_attributes , :only =>[:create, :destroy]
      end
    end
    resources :process_pools
    resources :resource_pools do
      resources :sim_resources
      resources :tower_cranes
    end
    resources :gannt_charts
    resources :sim_szenarios do
      resources :sim_results
    end   
  end
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  devise_for :users  
  resources :rpms
  resources :sim_events , :only =>[:index]
  resources :events_reports, :only =>[:index]
  resources :sim_events do
    collection {post :search, to: 'sim_events#index'}
  end
  
  resources :standard_resources
  resources :qto_items
  resources :building_elements
  resources :links
  resources :lv_items  
  resources :attributs
  resources :standard_colors
  resources :bim_filters    
  resources :task_attributes

  root :to => 'welcome#index'
  
  
  

end

app/models/task_attribute.rb
class TaskAttribute < ActiveRecord::Base
  belongs_to :task
  attr_accessible :AttName, :AttType, :AttValue , :task_id , :prerequisite_attributes
end

app/controllers/task_attributes_controller.rb
class TaskAttributesController < ApplicationController
  before_filter :authenticate_user!
  # GET /task_attributes
  # GET /task_attributes.json    
  def index
    @task_attributes = TaskAttribute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @task_attributes }
    end
  end

  # GET /task_attributes/1
  # GET /task_attributes/1.json
  def show
    @task_attribute = TaskAttribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task_attribute }
    end
  end

  # GET /task_attributes/new
  # GET /task_attributes/new.json
  def new
    @task_attribute = TaskAttribute.new	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task_attribute }
    end
  end

  # GET /task_attributes/1/edit
  def edit
    @task_attribute = TaskAttribute.find(params[:id])
  end

  # POST /task_attributes
  # POST /task_attributes.json
  def create  
    @task_attribute = TaskAttribute.new(params[:task_attribute])	
	@task_attribute.save
	@response = @task_attribute.errors #Errors
    @task_attribute = TaskAttribute.where(:task_id => params[:task_attribute][:task_id]).all
    @task = Task.find_by_id(params[:task_attribute][:task_id])
    respond_to do |format|
            format.js # new.html.erb
     end
  end

  # PUT /task_attributes/1
  # PUT /task_attributes/1.json
  def update
    @task_attribute = TaskAttribute.find(params[:id])
    respond_to do |format|
      if @task_attribute.update_attributes(params[:task_attribute])
        #format.html { redirect_to @task_attribute, notice: 'Task attribute was successfully updated.' }
		format.html{ redirect_to tasks_url }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_attributes/1
  # DELETE /task_attributes/1.json
  def destroy
    TaskAttribute.find(params[:id]).destroy
	@dtask = Task.find_by_id(params[:task_id])
    @task_attributes = @task.task_attributes if @task != nil
	 respond_to do |format|
      format.html { redirect_to task_attributes_url }
      format.json { head :no_content }
	  format.js {}
    end
	
   
  end
end

app/helpers/task_attributes_helper.rb
module TaskAttributesHelper
end

app/views/task_attributes/_form.html.erb
<%= form_for(@task_attribute) do |f| %>
  <% if @task_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_attribute.errors.count, "error") %> prohibited this task_attribute from being saved:</h2>

      <ul>
      <% @task_attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AttName %><br />
    <%= f.text_field :AttName %>
  </div>
  <div class="field">
    <%= f.label :AttValue %><br />
    <%= f.text_field :AttValue %>
  </div>
  <div class="field">
    <%= f.label :AttType %><br />
    <%= f.text_field :AttType %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_attributes/_task_attribute_list.html.erb
<table>
<tr><th>Attribute name</th><th>Attribute value</th><th></th></tr>
<% @task_attributes.each do |att| %>
<tr>
	<th><%= att.AttName %></th>
	<td><%= att.AttValue %></td>
	<td> <%= link_to task_attribute_path(att, :task_id => @task.id), :method => :delete, :confirm => 'Delete this Attribute?', :remote => true do |l| %>Delete<% end %></td>
</tr>
<% end %>
</table>

app/views/task_attributes/create.js.erb
//The first line updates the reference list (with the new Reference).
$('ul.task_attribute_list').html("<%= escape_javascript(render('task_attributes/task_attribute_list')) %>");
//This second line removes the text that was within the textarea (looks nicer and avoids duplication).
$('textarea.AttName').val("");
$('textarea.AttValue').val("");

app/views/task_attributes/destroy.js.erb
$('ul.task_attribute_list').html("<%= escape_javascript(render('task_attributes/task_attribute_list')) %>");

app/views/task_attributes/edit.html.erb
<h1>Editing task_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_attribute %> |
<%= link_to 'Back', task_attributes_path %>

app/views/task_attributes/index.html.erb
<h1>Listing task_attributes</h1>

<table>
  <tr>
    <th>Attname</th>
    <th>Attvalue</th>
    <th>Atttype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task_attributes.each do |task_attribute| %>
  <tr>
    <td><%= task_attribute.AttName %></td>
    <td><%= task_attribute.AttValue %></td>
    <td><%= task_attribute.AttType %></td>
    <td><%= link_to 'Show', task_attribute %></td>
    <td><%= link_to 'Edit', edit_task_attribute_path(task_attribute) %></td>
    <td><%= link_to 'Destroy', task_attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task attribute', new_task_attribute_path %>

app/views/task_attributes/new.html.erb
<h1>New task_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', task_attributes_path %>

app/views/task_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Attname:</b>
  <%= @task_attribute.AttName %>
</p>

<p>
  <b>Attvalue:</b>
  <%= @task_attribute.AttValue %>
</p>

<p>
  <b>Atttype:</b>
  <%= @task_attribute.AttType %>
</p>


<%= link_to 'Edit', edit_task_attribute_path(@task_attribute) %> |
<%= link_to 'Back', task_attributes_path %>